todo/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title= "TODO API",
        default_version="v1",
        description= "This is API endpoints for TODO project."
    ),
    public = True,
    permission_classes=[permissions.AllowAny,]
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("todofeature.urls", namespace="todofeature")),
    path("user/", include("useraccount.urls", namespace="user")),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$',schema_view.without_ui(cache_timeout=0),name='schema-json'),
    re_path(r'^swagger/$',schema_view.with_ui('swagger',cache_timeout=0),name='schema-swagger-ui'),
    re_path(r'^redoc/$',schema_view.with_ui('redoc',cache_timeout=0),name='schema-redoc'),
]
# +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todofeature/urls.py
from django.urls import path, include
from todofeature.views import todo_list_view, todo_add_view, todo_edit_view,todo_delete_view, demo_for_ajax
from rest_framework import routers
from todofeature.viewsets import TaskViewSet

app_name = "todofeature"

router = routers.SimpleRouter()
router.register("todo-api", TaskViewSet, basename="tasks")

urlpatterns = [
    path("",todo_list_view, name = "todo_list"),
    path("todo-add/",todo_add_view, name="todo_add"),
    path("todo-edit/<int:taskid>/", todo_edit_view, name="todo_edit"),
    path("todo-delete/", todo_delete_view, name="todo_delete"),
    path("demo-for-ajax/",demo_for_ajax, name="demo_for_ajax"),
    path("api/",include(router.urls)),
]

useraccount/urls.py
from django.urls import path
from useraccount.views import UserLoginView, SignUpView
from django.contrib.auth.views import LogoutView

app_name="user"

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", SignUpView.as_view(), name="register"),
]

todofeature/models.py
from django.db import models


class TimeStampModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    
    # to not create a physical table
    class Meta:
        abstract = True 
        
    
class Category(TimeStampModel):
    name =  models.CharField(max_length=255)
    
    class Meta:
        verbose_name = "Category"
        verbose_name_plural ="Categories"
        
    def __str__(self):
        return self.name
    
class Label(TimeStampModel):
    name = models.CharField(max_length=255)
    
    def __str__(self):
        return self.name

class Priority(models.TextChoices):
    LOWEST = "lowest", "Lowest"
    LOW = "low", "Low"
    MEDIUM = "medium","Medium"
    HIGH = "high", "High"
    HIGHEST = "highest","Highest"
   
class Task(TimeStampModel):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True) #blank for html, null for database
    image = models.ImageField(upload_to="todolist", blank=True, null=True)
    task_date = models.DateField(blank=True, null=True)
    priority = models.CharField(max_length=100, choices = Priority.choices, default = Priority.LOWEST)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    labels =  models.ManyToManyField(Label, blank = True)
    is_done = models.BooleanField(default=False)
    
    def __str__(self):
        return self.name

useraccount/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    address = models.CharField(max_length=255, blank=True, null=True)
    contact = models.CharField(max_length=255, blank=True, null=True)
    

todofeature/forms.py
from django import forms
from todofeature.models import Task

class TaskForm(forms.ModelForm):
    
    class Meta:
        model = Task
        fields = "__all__"
        #exclude = ("image", )
        # widgets = {
        #     'name' : (forms.TextInput(attrs={'class':'form-control', 'placeholder':'Your Name'})),
        #     'description' : (forms.Textarea(attrs={'class':'form-control', 'row':3, 'placeholder':'Write something....'})),
        #     'image' : (forms.FileInput(attrs={'class':'form-control-2', 'id' : 'image_field'})),
        #     'task_date' : (forms.SelectDateWidget),
        #     'priority' : (forms.Select(attrs={'class':'form-control'})),
        #     'category' : (forms.Select(attrs={'class':'form-group'})),
        #     'labels' : (forms.CheckboxSelectMultiple(attrs={'class':'form-group'})),

        # }
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"]="form-control"
        
        
    def clean_name(self):
        name = self.cleaned_data.get("name")
        if name.isdigit():
            raise forms.ValidationError("Name cannot be number")
        return name

useraccount/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()

class UserSignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username","password1","password2",)

todofeature/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django import forms 
from todofeature.forms import TaskForm
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from todofeature.models import Task
from django.contrib.auth.decorators import login_required


# from django.contrib.auth.mixins import LoginRequiredMixin
# class TaskCreateView(LoginRequiredMixin,CreateView):
#     #this works like a login_required decorator for class based view

    
def todo_list_view (request):
    tasks = Task.objects.all().order_by("id")
    context = {"tasks": tasks}
    return render(request,"todo_list.html", context)

@login_required
def todo_add_view(request):
    # print(request.POST)
    form = TaskForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse("todofeature:todo_list"))
    return render(request, "add_todo.html", {'form':form})

def todo_edit_view(request, taskid):
    task = get_object_or_404(Task, id = taskid)
    # try:
    #     Task.objects.get(id=taskid)
    # except Task.DoesNotExist:
    #     raise Http404()
    form = TaskForm(request.POST or None, instance=task)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse("todofeature:todo_list"))
    return render(request,"add_todo.html",{"form":form})

# def todo_delete_view(request, taskid):
#     task = get_object_or_404(Task, id = taskid)
#     task.delete()
#     return HttpResponseRedirect(reverse("todofeature:todo_list"))

def todo_delete_view(request):
    taskid = request.POST.get('taskid')
    task = get_object_or_404(Task,id=taskid)
    task.delete()
    return HttpResponseRedirect(reverse("todofeature:todo_list"))
    
def demo_for_ajax(request):
    data = {"name": "Ram", "address": "Kathmandu"}
    return JsonResponse(data, safe=False)

useraccount/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
from django.views.generic import CreateView
from django.contrib.auth import get_user_model
from useraccount.forms import UserSignupForm

User= get_user_model()

class UserLoginView(LoginView):
    template_name = "login.html"
    redirect_authenticated_user=True


class SignUpView(CreateView):
    model = User
    form_class = UserSignupForm
    template_name = "register.html"
    success_url = reverse_lazy("todofeature:todo_list")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang = "en">
    <head>
        <title>
            {% if title %}
                {{ title }}
            {% else %}
                TODO
            {% endif %}
        </title>
        {% block stylesheet %}
            <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        {% endblock stylesheet %}
        
    </head>
    <body>
        <div class="container">
            {% block content %}
                
            {% endblock content %}

            {% block script %}
                <script src="{% static 'js/jquery.min.js' %}"></script>
                <script src="{% static 'js/jquery-ajax.min.js' %}"></script>
                <script src="{% static 'js/bootstrap-min.js' %}"></script>
            {% endblock script %}
        </div>
    </body>
</html>

templates/base_site.html
{% extends 'base.html' %}

{% block content %}

    {% include 'navbar.html' %}

    {% block maincontent %}
    {% endblock maincontent %}

{% endblock content %}

templates/navbar.html
{% comment %} <ul>
    <li>
        <a href="{% url 'todofeature:todo_list' %}">List Todo</a>
    </li>

    <li>
        <a href="{% url 'todofeature:todo_add' %}">Add Todo</a>
    </li>
</ul> {% endcomment %}

 <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <b><a class="nav-link" href="{% url 'todofeature:todo_list' %}">List Todo</a></b>
        </li>
        <li class="nav-item">
          <b><a class="nav-link" href="{% url 'todofeature:todo_add' %}">Add Todo</a></b>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <b><a class="nav-link" href="{% url 'user:logout' %}">Log Out</a></b>
        </li>
        {% endif %}

        {% if not request.user.is_authenticated %}
        <li class="nav-item">
          <b><a class="nav-link" href="{% url 'user:login' %}">Log In</a></b>
        </li>
        <li class="nav-item">
          <b><a class="nav-link" href="{% url 'user:register' %}">Register</a></b>
        </li>
        {% endif %}

      </ul>
    </div>
  </nav>

todofeature/templates/add_todo.html
{% extends 'base_site.html' %}

{% block maincontent %}

<form action="" method="post"> {% csrf_token %}
    
    {% comment %} {{ form.as_p}} {% endcomment %}
    
    {{ form.non_field_errors }}
    {% for field in form %}
        <div class="form-group">
            {{ field.label_tag}}
            {{ field }}
            <div class="text text-danger">
                {{ field.errors }}
            </div>
        </div>
    {% endfor %}
    <input type="submit" class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off" value="Submit" name="submit"/>
</form>

{% endblock maincontent %}

todofeature/templates/todo_list.html
{% extends 'base_site.html' %}

{% block maincontent %}
    <h1>My Todo List</h1>
    {% comment %} {% for task in tasks %}
        <p>{{task.name}}</p>
        <p>{{task.description}}</p>
        <p>{{task.priority}}</p>
        <p>..........................</p>
    {% endfor %} {% endcomment %}

    <b><table class ="table table-stripped table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description </th>
                <th>Priority</th>
                <th>Action</th>
            </tr>
        </thead>
        
        <tbody>
            {% for task in tasks %}

                {% if task.priority == 'highest' or task.priority == 'high' %}
                    <tr class="p-3 mb-2 bg-danger text-white">
                        <td>{{task.id}}</td>
                        <td>{{task.name}}</td>
                        <td>{{task.description}}</td>
                        <td>{{task.priority}}</td>
                        <td>
                            <a href="{% url 'todofeature:todo_edit' task.id %}">
                                <input 
                                type="submit" 
                                class="btn btn-primary" 
                                data-toggle="button" 
                                aria-pressed="false" 
                                autocomplete="off" 
                                value="Edit" 
                                name="edit"/>
                            </a>
                            <button href=""
                            type="button"
                            class="btn btn-primary"
                            data-taskid="{{task.id}}"
                            data-bs-toggle="modal"
                            data-bs-target="#myModal"
                            >
                                Delete
                            </button>
                        </td>
                    </tr>
                {% endif %}

                {% if task.priority == 'medium' %}
                    <tr class="p-3 mb-2 bg-warning text-white">
                        <td>{{task.id}}</td>
                        <td>{{task.name}}</td>
                        <td>{{task.description}}</td>
                        <td>{{task.priority}}</td>
                        <td>
                            <a href="{% url 'todofeature:todo_edit' task.id %}">
                                <input 
                                type="submit" 
                                class="btn btn-primary" 
                                data-toggle="button" 
                                aria-pressed="false" 
                                autocomplete="off" 
                                value="Edit" 
                                name="edit"/>
                            </a>
                            <button href=""
                            type="button"
                            class="btn btn-primary"
                            data-taskid="{{task.id}}"
                            data-bs-toggle="modal"
                            data-bs-target="#myModal"
                            >
                                Delete
                            </button>
                        </td>
                    
                    </tr>
                {% endif %}

                {% if task.priority == 'lowest' or task.priority == 'low' %}
                    <tr class="p-3 mb-2 bg-success text-white">
                        <td>{{task.id}}</td>
                        <td>{{task.name}}</td>
                        <td>{{task.description}}</td>
                        <td>{{task.priority}}</td>
                        <td>
                            <a href="{% url 'todofeature:todo_edit' task.id %}">
                                <input 
                                type="submit" 
                                class="btn btn-primary" 
                                data-toggle="button" 
                                aria-pressed="false" 
                                autocomplete="off" 
                                value="Edit" 
                                name="edit"/>
                            </a>
                            <button href=""
                            type="button"
                            class="btn btn-primary"
                            data-taskid="{{task.id}}"
                            data-bs-toggle="modal"
                            data-bs-target="#myModal"
                            >
                                Delete
                            </button>
                        </td>
                        
                    </tr>
                {% endif %}

                <!-- Modal -->
                <div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                        Are you sure you want to delete???
                        </div>
                        <form id="delete-form" action="{% url 'todofeature:todo_delete' %}"  method="post">
                            {% csrf_token %}
                            <input type="hidden" name="taskid" id="_taskid">
                        </form>
                        <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" id="delete-button" class="btn btn-primary">Yes</button>
                        </div>
                    </div>
                    </div>
                </div>

            {% endfor %}
        </tbody>

        
    </table><b>
{% endblock maincontent %}

{% block script %}

{{block.super}}
<script type="text/javascript">
    $(document).ready(function(){
        $.ajax({
            url: '/demo-for-ajax/',
            type: 'GET',
            dataType: 'json',
            success:function(res){
                console.log(res);
            },
            error:function(res){
                console.log(res);
            }
        });

        let model = document.getElementById("myModal");
        model.addEventListener("show.bs.modal",function(evt){
            let btn = evt.relatedTarget;
            let taskid = btn.dataset.taskid;
            $("#_taskid").val(taskid);
        });
        $('#delete-button').click(function(){
            $("#delete-form").submit();
        });
    });
</script>
{% endblock script %}

useraccount/templates/login.html
{% extends 'base.html' %}

{% block content %}
<form method="post" action="">{% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-primary" value="Log In"/>
</form>
{% endblock content %}

useraccount/templates/register.html
{% extends 'base.html' %}

{% block content %}
<form method="post" action="">{% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-primary" value="Sign Up"/>
</form>
<a class="nav-link" href="{% url 'user:login' %}">Log In</a>
{% endblock content %}